filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /home/herion/app/mylog.log
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
      max_lines: 1000
      timeout: 3s
output.elasticsearch:
  hosts: ["127.0.0.1:19200","127.0.0.1:29200"]
  index: "log-eureka-%{+yyyy.MM}"
setup.template.name: "log-eureka"
setup.template.pattern: "log-eureka-*"